### PR TITLE
fix: add a flag to track completion status in connectToProtectedSSIDOnce

### LINKED ISSUE #429: WifiManager.connectToProtectedSSID(): Tried to resolve a promise more than once
Hello,

Im using expo to develop and app to connect to an IOT device and send a binary file over, after its created a web server.

Getting this weird error, on iOS only, when using:

- connectToProtectedSSID
-connectToProtectedWifiSSID (with any timeout )
-connectToSSID (conditionally based on platform).

I am able to successfully connect to the wifi created by the IOT, but this error is thrown outside the app, and breaks it.
It even passes this function and moves onto the next function (where I send the binary file), but as soon as I try to hit the pOST endpoint it throws this error

Doesn't happen on Android.

Here is my function:

```
const connectToWebServer = async () => {
    setIsConnectingToWebServer(true);
    await delay(3000);
    const currentWifiSSID = await WifiManager.getCurrentWifiSSID();
    try {

    let wifiList: WifiEntry[];
    let ssidExists: boolean | null = null;

    if(Device.osName === "Android"){
      wifiList= await WifiManager.reScanAndLoadWifiList(); //Not on iOS
      ssidExists = wifiList.some((wifi) => wifi.SSID.trim() === OTA_SSID);
    }

      if (ssidExists || Device.osName === "iOS") {
        const initialSSID = await WifiManager.getCurrentWifiSSID();
        if(Device.osName === "iOS") {
          await WifiManager.disconnectFromSSID(initialSSID);
        } else {
          await WifiManager.disconnect();
        }

        await WifiManager.connectToProtectedSSID(
          OTA_SSID,
          null,
          false,
          false
        );
        
        const newSSID = await WifiManager.getCurrentWifiSSID();
        if (newSSID === OTA_SSID) {
          setIsConnectedToWebServer(true);
        }
      } else {
        setIsUpdateError(true);
        setIsConnectedToWebServer(false);
        throw new Error("SSID doesn't exist!");
      }
    } catch (error) {
        // Error catching
    }
  };
```

Has anyone faced a similar issue? Any help would be appreciated.

### PR DESCRIPTION
**Pull request by haraldmartin**
I took [SynidSweet](https://github.com/SynidSweet)'s suggestion from https://github.com/JuanSeBestia/react-native-wifi-reborn/issues/429 and created a PR.
Fixes #429

### CODE REVIEW

**Comment by notjulian** [comment]
Hi @elliottkember ,
do you mind to check this one please ...
thanks in advance

File: ios/RNWifi.m [hunk 1]
```diff
@@ -187,14 +188,25 @@ + (BOOL)requiresMainQueueSetup
...
+                        }
                         [self getWifiSSID:^(NSString* newSSID) {
+                            // Return early if we've already completed
+                            if (hasCompleted) {
+                                return;
+                            }
                             bool success = [ssid isEqualToString:newSSID];
                             tries++;
 
                             if (success){
```
Comment (DavideViolante) [inline ios/RNWifi.m:204]:
```suggestion
                            if (success) {
```

File: ios/RNWifi.m [hunk 2]
```diff
@@ -179,6 +179,7 @@ + (BOOL)requiresMainQueueSetup
                     // the connection is successful.
                     __block int tries = 0;
                     __block int maxTries = 20;
+                    __block BOOL hasCompleted = NO; // Add a flag to track completion status
```
Comment (DavideViolante) [inline ios/RNWifi.m:182]:
```suggestion
                    __block BOOL hasCompleted = NO; // Add a flag to track completion status, fixes #429
```

File: ios/RNWifi.m [hunk 3]
```diff
@@ -203,6 +215,7 @@ + (BOOL)requiresMainQueueSetup
                         }];
                     });
 
+
```
Comment (DavideViolante) [inline ios/RNWifi.m:218]:
```suggestion
```

**Comment by DavideViolante** [comment]
LGTM

**Comment by JuanSeBestia** [comment]
LGTM too
